name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job triggered by ${{ github.event_name }}"
          echo "This branch is ${{ github.ref }} and repo is ."

      - uses: actions/checkout@v4

      - name: List files
        run: |
          echo "The repo ${{ github.repository }} has:"
          tree
